### PR TITLE
A developer can build and deliver a deb package

### PR DESCRIPTION
**Pull request by rosscooperman**

### CODE REVIEW

**Comment by rosscooperman** [comment]
@paulijones I think for now we should just host the .deb files as releases on GitHub. I can rewrite the installation instructions to match. Actually hosting the package in PPA/Launchpad (Ubuntu's thing) is a lot more involved. You have to upload source packages there and then they do the build which is complicated with golang projects.

**Comment by paulijones** [comment]
This looks good to me, do we want to get the readme merged first? or will we do the install updates in a separate pr?

**Comment by rosscooperman** [comment]
We should get the README merged first I think and then I can update in this PR

**Comment by rosscooperman** [comment]
@paulijones README updated, ready for a real review 😄

**Pull request merged**
