### PR TITLE
Paulijones/ch3471/a user can configure loom to write its output

### PR DESCRIPTION
**Pull request by paulijones**

### CODE REVIEW

**Comment by paulijones** [comment]
im aware we took a coverage hit. we decided not to spin up a web server for testing

**Comment by rosscooperman** [comment]
@paulijones test failures?

**Comment by paulijones** [comment]
re-running fixed it, which is worrisome? it was panicking on the file rename after its been flushed to the fs...
claimed the file didn't exist

**Comment by paulijones** [comment]
@rosscooperman thoughts?

**Comment by rosscooperman** [comment]
Yeah @paulijones, that's a little concerning. Has all the hallmarks of a race condition 😟.

**Comment by paulijones** [comment]
@rosscooperman 
did-a-business

**Pull request merged**
